---
- name: yum - Install postfix packages on CentOS 7
  when:
    (
      ansible_distribution == "CentOS" and
      ansible_distribution_major_version == "7" and
      (
        item.value.state == "present" or
        item.value.state == "latest"
      ) and
      item.value.CentOS is defined and
      item.value.CentOS.7 is defined
    )
  yum:
    name: "{{ item.value.CentOS.7 }}"
    state: "{{ item.value.state }}"
  with_dict: "{{ aspects_postfix_packages }}"
  tags:
    - aspects_postfix
    - aspects_postfix_package_install
    - aspects_postfix_package_install_yum
